spring:
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/test
    username: test
    password: secret
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
